# 配置端口
server:
  port: 8090
  servlet:
    context-path: /mangkdian         # 访问path
  tomcat:
    uri-encoding: UTF-8     # 默认编码格式
    max-threads: 1000       # 最大线程数量 默认200
    min-spare-threads: 30   # 初始化启动线程数量
  address: 0.0.0.0

spring:
  profiles:
    #  配置的环境
    #    active: #spring.profiles.active#
    active:
  servlet:
    multipart:
      max-file-size: 50MB #设置单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小
  application:
    name: mangkeyshop #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.196.200.233:3306/front?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=GMT+8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: Monkey2024@0722
  mvc:
    async:
      request-timeout: 120000
debug: true
logging:
  level:
    org.springframework: DEBUG
    springfox: DEBUG


# mybatis 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  # 配置slq打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #      logic-delete-field: isDel  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jwt:
  secret: zXpLQVJtRlFzZzJhZkNvZGdWbW5oU25KQ0xPQ21tR2NqZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2NjZ2
  expiration: 15552000

wechat:
  appid: wx70a5bdceab3fb46b
  secret: d20f48738166db1d0e2ee43601bb3659
